cmake_minimum_required(VERSION 4.1)
project(TareaXIII)

set(CMAKE_CXX_STANDARD 20)

add_executable(TareaXIII main.cpp
        Ejercicio1.cpp
        Ejercicio1.h
        Ejercicio2.cpp
        Ejercicio2.h
        Ejercicio3.cpp
        Ejercicio3.h
        Ejercicio4.cpp
        Ejercicio4.h
        Ejercicio5.cpp
        Ejercicio5.h
        Ejercicio6.cpp
        Ejercicio6.h
        Ejercicio7.cpp
        Ejercicio7.h)
